import manifest from "./assets.json";

export type AssetMeta = { width: number; height: number; blur: string };

const map = manifest as Record<string, AssetMeta>;

// Returns optimized dimensions + blur placeholder generated by the asset pipeline.
// Falls back to a sane default so the UI never breaks if an asset is missing.
export function getAsset(src: string): AssetMeta {
  return (
    map[src] ?? {
      width: 1600,
      height: 1000,
      blur:
        "data:image/webp;base64,UklGRiIAAABXRUJQVlA4IBYAAAAwAQCdASoBAAEADsD+JaQAA3AAAAAA",
    }
  );
}
