// Full EN/AR dictionary, every user-facing string on the site lives here.
// Components read dict[lang] via useLang().

export type Lang = "en" | "ar";

const en = {
  nav: {
    work: "Work",
    about: "About",
    contact: "Contact",
    letsTalk: "Let's talk",
    roleTag: "· Sr Designer, Team Lead",
    langBtn: "عربي",
  },
  hero: {
    avail: "Available, Full-time · Remote · Freelance · Hybrid",
    portfolio: "Portfolio · 2026",
    intro: "Mohamed Tarek · Sr Designer, Team Lead · based in Egypt",
    l1: "The graphic designer",
    l2: "brands call when they",
    l3pre: "need to be",
    l3accent: "unmissable.",
    ctaPrimary: "Selected work",
    ctaSecondary: "Hire me ↗",
    markets:
      "Working across Egypt · Saudi Arabia · Kuwait, strategy first, craft always.",
    chipRole: "SR DESIGNER, TEAM LEAD · EGYPT",
    chipBadge: "ART DIRECTION",
  },
  work: {
    label: "Selected Work",
    h2a: "Work, organised by the",
    h2i: "industry",
    h2b: "it was built for.",
    note: "Case studies grouped by industry, pick a sector, open a case.",
    viewCase: "VIEW CASE ↗",
    sectors: {
      "AI Workflow": "AI Workflow",
      Technology: "Technology",
      "Food & Retail": "Food & Retail",
      "Real Estate": "Real Estate",
      "Marketing & Agency": "Marketing & Agency",
      Hospitality: "Hospitality",
      Automotive: "Automotive",
    } as Record<string, string>,
    blurbs: {
      "AI Workflow":
        "AI-produced photo and video campaigns, planned as a system, from first prompt to final asset library.",
      Technology:
        "Cybersecurity and HR-SaaS campaigns, complex products made human, in Arabic and English.",
      "Food & Retail":
        "Premium gifting and produce brands, identity, packaging and campaigns that sell the feeling.",
      "Real Estate":
        "Bilingual AR/EN campaigns for luxury developments in Makkah and the Gulf.",
      "Marketing & Agency":
        "3D concept campaigns and scalable social systems for agencies and multi-brand feeds.",
      Hospitality:
        "B2B hospitality supply made five-star, cinematic key visuals and cross-channel social.",
      Automotive:
        "Geely & GWM key visuals, retouching, colour grading and calm, premium light.",
    } as Record<string, string>,
  },
  // Per-project card + case copy (slug-keyed). Anything missing falls back EN.
  projects: {} as Record<
    string,
    { title?: string; tagline?: string; category?: string; challenge?: string; strategy?: string }
  >,
  ai: {
    label: "AI Work Flow",
    h2a: "The process comes",
    h2i: "first",
    h2b: ", then the work.",
    note: "Two productions planned as systems: read the flow, then see what it produced.",
    pick: "Pick a production",
  },
  master: {
    label: "Master Visuals",
    h2a: "The campaign boards, and the",
    h2i: "thinking",
    h2b: " behind them.",
    note: "Key visuals with the concept, my role and the craft that built them. Click any board to view it larger.",
    expand: "view larger",
    close: "Close",
  },
  socialCards: {
    label: "Social Media Designs",
    h2a: "One brand, one",
    h2i: "system",
    h2b: ", every post.",
    note: "Each brand gets a key visual and a repeatable post system, so the feed stays on brand at posting speed.",
    keyVisual: "Key visual",
    posts: "designs",
    viewAll: "View the full set →",
  },
  story: {
    label: "Storyboards",
    h2a: "Every film is drawn",
    h2i: "before",
    h2b: " it is shot.",
    note: "Frame-by-frame boards that lock the story, the shots and the pacing before production starts.",
    board: "Board",
  },
  clients: {
    label: "Clients",
    h2a: "Brands I have",
    h2i: "worked with",
    h2b: ".",
    note: "Across real estate, F&B, retail, SaaS, hospitality and education in Egypt, Saudi Arabia and Kuwait.",
  },
  services: {
    label: "Services",
    h2a: "What I can",
    h2i: "do",
    h2b: "for your brand.",
    note: "Available for full-time, remote, freelance and hybrid roles, ",
    noteLink: "start a conversation ↗",
    items: [
      {
        title: "Brand Identity",
        desc: "Logos, visual systems, packaging and guidelines, identities built to scale from a business card to a delivery fleet.",
        tags: ["Logo & Wordmark", "Visual System", "Packaging"],
      },
      {
        title: "Campaigns & Key Visuals",
        desc: "Advertising campaigns and hero visuals for real estate, automotive, SaaS and hospitality, concept to final art.",
        tags: ["Campaign Concept", "Key Visuals", "Bilingual AR/EN"],
      },
      {
        title: "Social Media Systems",
        desc: "Repeatable, on-brand feeds, grids, templates and content systems that keep quality high at posting speed.",
        tags: ["Templates", "Content Design", "Feed Systems"],
      },
      {
        title: "Art & Creative Direction",
        desc: "Leading designers and owning the visual language, briefs, reviews and standards that lift the whole output.",
        tags: ["Team Leadership", "Concepting", "Quality Control"],
      },
      {
        title: "AI-Assisted Production",
        desc: "Campaign-grade imagery and AI voice-over produced with AI tooling, directed, curated and finished to a professional standard.",
        tags: ["AI Imaging", "Prompt Engineering", "AI Voice-Over", "Retouching"],
      },
      {
        title: "Motion & Web",
        desc: "Reels, promos and edits, plus designed-and-shipped websites, vibe-coded end to end like this portfolio.",
        tags: ["Video & Reels", "Motion Graphics", "Web Design"],
      },
    ],
  },
  motion: {
    label: "Motion & Video",
    h2a: "When a still isn't",
    h2i: "enough",
    h2b: ".",
    note: "Brand films, social reels and animation, tap the speaker to hear it, or expand any clip to watch larger.",
    landscape: "Landscape",
    portrait: "Portrait",
  },
  type: {
    label: "Type Design",
    h2a: "Letters drawn",
    h2i: "by hand",
    h2b: ".",
    note: "Custom Arabic and Latin lettering, logotypes, campaign headlines and wordmarks built letter by letter.",
  },
  web: {
    label: "Vibe Coding",
    h2a: "I design, then I",
    h2i: "ship the code",
    h2b: ".",
    note: "Live websites I designed and built through vibe coding, AI-assisted development. Even this portfolio is vibe-coded. Pick one to preview it.",
    live: "Live ↗",
    visit: "Open live site",
    sites: "sites shipped",
  },
  social: {
    label: "Selected designs, a continuous wall of work",
    browse: "Browse the work ↑",
  },
  hire: {
    avail: "FULL-TIME · REMOTE · FREELANCE · HYBRID",
    h2a: "Have a brand that needs",
    h2i: "direction",
    h2b: "?",
    body: "I am open to full-time, remote, freelance and hybrid roles across Egypt · Saudi Arabia · Kuwait. Tell me what you're building, I'll tell you how design gets it there.",
    wa: "WhatsApp me ↗",
    all: "All contact options",
  },
  footer: {
    blurb:
      "Sr Designer & Team Lead based in Egypt, working across Egypt · Saudi Arabia · Kuwait. Available for full-time, remote, freelance and hybrid roles.",
    siteCol: "Site",
    connectCol: "Connect",
    rights: "Designed, art-directed & vibe-coded in-house.",
    backTop: "Back to top ↑",
  },
  about: {
    label: "About",
    heroBio:
      "More than five years turning business problems into visual answers: brand identities, campaigns and social systems for companies across Egypt, Saudi Arabia and Kuwait. Today I lead a design team, and I am looking for the next place to build one.",
    intro1: "A designer who leads, treating every brand as a",
    introAccent: "business problem",
    intro2: "with a creative answer.",
    bio1: "I'm Mohamed Tarek, a Sr Designer and Team Lead, based in Egypt with professional experience across the Egyptian, Saudi and Kuwaiti markets, focused on clean, strategic, performance-driven design that strengthens brand identity and supports real marketing objectives.",
    bio2: "I work across branding, campaigns, social systems, key visuals and motion, skilled in Adobe Photoshop and Illustrator, UI design, and AI-powered creative tools I use to ideate and deliver modern work tailored to Middle East markets. Alongside client work, I teach graphic design as an instructor, mentoring the next wave of designers.",
    coreFocus: "Core focus",
    traitsLabel: "Personal traits",
    focus: ["2D Visual Design", "Brand Systems", "AI Prompt Engineering", "AI Voice-Over"],
    traits: [
      "Creative & Strategic Thinker",
      "Performance-Driven",
      "Detail-Oriented",
      "Fast Learner & Adaptive",
      "Strong Visual Consistency",
      "Collaborative Team Player",
    ],
  },
  exp: {
    label: "Experience",
    h2a: "The companies that",
    h2i: "shaped",
    h2b: "me.",
    note: "Across Egypt & Saudi Arabia, newest first. From graphic designer, to teaching, to leading an art team.",
    now: "Now",
    promoted: "↑ Promoted",
    returned: "↩ Returned to lead",
    earlier: "Earlier at Osolutions · three years of promotions",
    filterHint: "Filter by commitment",
    all: "All roles",
    fullTime: "Full-time",
    partTime: "Part-time · Remote",
  },
  teach: {
    label: "Teaching",
    h2a: "I don't just lead designers, ",
    h2i: "I make them",
    h2b: ".",
    note: "Instructor across four academies, and an on-call advisor, visiting teams to solve design problems on the ground.",
    statNote:
      "Close to 1,200 students graduated across 49 cohorts, numbers are approximate, and still counting.",
    stats: [
      { n: "~1,200", l: "students graduated" },
      { n: "49", l: "cohorts taught" },
      { n: "4", l: "academies" },
    ],
    current: "Current",
    role: "Design Instructor",
    academies: [
      {
        name: "SOIC, School of Cinema",
        logo: "/orgs/soic.webp",
        now: true,
        desc: "Teaching design craft inside a filmmaking school, visual storytelling, key art and campaign thinking for cinema.",
      },
      {
        name: "EDUX Academy",
        logo: "/orgs/edux.webp",
        now: true,
        desc: "Graphic design tracks taking students from fundamentals to portfolio-ready execution.",
      },
      {
        name: "Easily",
        now: false,
        desc: "Full essentials journey, Photoshop, Illustrator and Figma; ad campaigns, UI/UX, moodboards, storyboards, insights, concept development and execution.",
      },
      {
        name: "Raya Academy",
        logo: "/orgs/raya.webp",
        now: false,
        desc: "Hands-on graphic design cohorts, photo manipulation, landing pages and branding, taught project by project.",
      },
    ],
  },
  process: {
    label: "Creative Process",
    h2a: "From a brief to a",
    h2i: "decision",
    h2b: ".",
    note: "Direction is decision-making, the path I take every brand through, from understanding to execution.",
    steps: [
      {
        n: "01",
        title: "Research",
        body: "I start with the business, the market and the audience, what the brand needs to achieve, and what everyone else is already saying.",
      },
      {
        n: "02",
        title: "Insight",
        body: "I find the one truth that unlocks the work, the tension that makes people care. The insight is the strategy in a single sentence.",
      },
      {
        n: "03",
        title: "Concept",
        body: "I translate the insight into a creative idea big enough to live across channels, a platform, not a poster.",
      },
      {
        n: "04",
        title: "Direction",
        body: "I define the visual language: type, colour, light and tone. The idea becomes a world with rules everyone can build on.",
      },
      {
        n: "05",
        title: "Execution",
        body: "I bring it to life and hold the bar across every touchpoint, from the hero frame to the smallest story.",
      },
    ],
  },
  skills: {
    label: "Capabilities",
    groups: [
      {
        title: "Direction & Strategy",
        items: ["Creative Direction", "Brand Strategy", "Campaign Design", "Creative Thinking"],
      },
      {
        title: "Craft & Systems",
        items: ["Visual Identity", "Social Media Systems", "Motion Design", "Marketing Communication"],
      },
      {
        title: "Production",
        items: ["Photo Manipulation", "Key Visuals", "UI Design", "AI Prompt Engineering", "AI Voice-Over (ElevenLabs)", "Vibe Coding"],
      },
    ],
  },
  tools: {
    label: "Toolkit",
    h2a: "Craft tools, sharpened with",
    h2i: "AI",
    h2b: ".",
    aiCol: "AI Toolkit",
    craftCol: "Design & Motion",
  },
  vision: {
    label: "Vision",
    h2a: "I want to turn a business problem into the",
    h2i: "idea",
    h2b: "everyone rallies behind.",
    pillars: [
      {
        k: "Where I am",
        v: "An art Team Lead with a designer's craft and a strategist's instinct, already leading the team and building work that performs in market.",
      },
      {
        k: "Where I'm heading",
        v: "Creative direction: owning concepts end to end, shaping visual languages, and raising the craft of the people around me.",
      },
      {
        k: "Why direction",
        v: "My strongest work was never about decoration, it's about decisions. That's where strategy, craft and leadership meet.",
      },
    ],
  },
  contact: {
    label: "Contact",
    h2a: "Let's make work that's",
    h2i: "remembered.",
    body: "Open to new roles, freelance projects and creative collaborations across Egypt · Saudi Arabia · Kuwait. If you're building something ambitious, I'd love to hear about it.",
    labels: {
      Email: "Email",
      WhatsApp: "WhatsApp",
      Phone: "Phone",
      LinkedIn: "LinkedIn",
    } as Record<string, string>,
    copy: "Copy",
    copied: "Copied",
    open: "Open",
  },
  case: {
    allWork: "All work",
    letsTalk: "Let's talk",
    challenge: "The Challenge",
    solution: "The Solution",
    ctaA: "Got a brand worth building?",
    ctaI: "Let's talk.",
    ctaBtn: "Start a conversation ↗",
    cont: "Continue",
    readMore: "See the full case",
    showAll: "Show all",
    finalVideos: "Final Videos",
    interactive: "Interactive",
    prev: "Previous",
    next: "Next",
  },
};

// ---------------------------------------------------------------- Arabic
const ar: typeof en = {
  nav: {
    work: "الأعمال",
    about: "عنّي",
    contact: "تواصل",
    letsTalk: "لنتحدث",
    roleTag: "· مصمم أول، قائد فريق",
    langBtn: "EN",
  },
  hero: {
    avail: "متاح، دوام كامل · عن بُعد · فريلانس · هجين",
    portfolio: "بورتفوليو · ٢٠٢٦",
    intro: "محمد طارق · مصمم أول، قائد فريق · مقيم في مصر",
    l1: "المصمّم الذي تناديه",
    l2: "العلامات التجارية حين",
    l3pre: "تريد أن تكون",
    l3accent: "لا تُنسى.",
    ctaPrimary: "أعمال مختارة",
    ctaSecondary: "وظّفني ↗",
    markets: "أعمل عبر مصر · السعودية · الكويت، الاستراتيجية أولًا، والحِرفة دائمًا.",
    chipRole: "مصمم أول، قائد فريق · مصر",
    chipBadge: "آرت دايركشن",
  },
  work: {
    label: "أعمال مختارة",
    h2a: "الأعمال، منظّمة حسب",
    h2i: "الصناعة",
    h2b: "التي صُمّمت لها.",
    note: "دراسات حالة مجمّعة حسب الصناعة، اختر قطاعًا وافتح الحالة.",
    viewCase: "عرض الحالة ↗",
    sectors: {
      "AI Workflow": "سير عمل الذكاء الاصطناعي",
      Technology: "التقنية",
      "Food & Retail": "الأغذية والتجزئة",
      "Real Estate": "العقارات",
      "Marketing & Agency": "التسويق والوكالات",
      Hospitality: "الضيافة",
      Automotive: "السيارات",
    },
    blurbs: {
      "AI Workflow":
        "حملات صور وفيديو منتجة بالذكاء الاصطناعي، مخطّطة كنظام، من أول برومبت لآخر أصل.",
      Technology:
        "حملات للأمن السيبراني وأنظمة الموارد البشرية، منتجات معقّدة تصل للناس ببساطة، بالعربية والإنجليزية.",
      "Food & Retail":
        "علامات هدايا ومنتجات مميّزة، هوية وتغليف وحملات تبيع الإحساس قبل المنتج.",
      "Real Estate": "حملات ثنائية اللغة لمشاريع فاخرة في مكة والخليج.",
      "Marketing & Agency":
        "حملات مفاهيم ثلاثية الأبعاد وأنظمة سوشيال قابلة للتوسّع للوكالات.",
      Hospitality:
        "توريدات الضيافة بمظهر خمس نجوم، صور رئيسية سينمائية وسوشيال متكامل.",
      Automotive: "الصور الرئيسية لجيلي وGWM، ريتاتش وتلوين وضوء هادئ فاخر.",
    },
  },
  projects: {
    'photo-sessions': {
      title: 'جلسات تصوير بالذكاء الاصطناعي، مكتبة منتجات متكاملة',
      tagline: 'من صور منتج عادية إلى مكتبة فاخرة ومتّسقة.',
      category: 'إنتاج صور بالذكاء الاصطناعي',
      challenge:
        'المنتجات كانت محتاجة مكتبة صور كبيرة ومتّسقة للحملات والسوشيال والمطبوعات. تصوير كل زاوية بالطريقة التقليدية كان هياخد وقت وميزانية أكبر بكتير من الجدول المتاح.',
      strategy:
        'خطّطت الجلسة بالكامل قبل أي إنتاج: حدّدت المنتجات والزوايا والشكل النهائي أولًا، وبعدين أنتجتها بأدوات الذكاء الاصطناعي وأنهيتها بالريتاتش، عشان كل إطار يشترك في نفس الإضاءة والتكوين والإحساس الفاخر.',
    },
    'video-production': {
      title: 'إنتاج فيديو بالذكاء الاصطناعي، نظام واحد مترابط',
      tagline: 'نظام واحد مخطّط، وأفلام كتير، بدل تصوير منفصل لكل فيديو.',
      category: 'إنتاج فيديو بالذكاء الاصطناعي',
      challenge:
        'الحملة كانت محتاجة كذا فيديو في نفس الوقت، أفلام رئيسية ومقاطع سوشيال ولقطات مساندة. التعامل مع كل واحد كمشروع منفصل كان هيكسر اللغة البصرية ويكرّر نفس الشغل مرات كتير.',
      strategy:
        'بنيت الحملة كنظام إنتاج واحد. الشخصيات والمشاهد اتحدّدت من البداية واتربطت ببعض، فاللقطة الواحدة المخطّطة تخدم أكتر من فيديو والحملة كلها تفضل بشكل واحد.',
    },
    amam: {
      title: 'أمام · درة العروس، حياة على الماء',
      tagline: 'بعنا الويك-إند، مش الأمتار.',
      category: 'عقارات · حملة',
      challenge:
        'درة العروس وجهة منتجعات، لكن معظم إعلانات العقارات في الفئة دي بتبيع مخططات وأسعار. أمام كانت محتاجة الفيد يخلّي الناس تحس بالحياة هناك قبل ما تسأل عن وحدة أصلًا.',
      strategy:
        'ابدأ باللحظات اللي الناس بتشتريها فعلًا: جيت سكي الضهر، ويخت وقت الغروب، ووقت عيلة جنب المسبح. كل بوست بيعرض حياة الأول والعقار تاني، ماسكهم خط عربي هادي واحد ونفس ضوء الماء الدافي.',
    },
    'el-raghi': {
      title: 'الراجحي، مبني ليدوم',
      tagline: 'بُني بإتقان ليمنحك جودة تدوم لسنوات.',
      category: 'عقارات · سوشيال',
    },
    'tilal-v': {
      title: 'تلال فيليدج، حيث تجد الحياة مكانها',
      tagline: 'بعنا الانتماء والإيمان، مش الأمتار.',
      category: 'عقارات · حملة سوشيال',
      challenge:
        'مجتمع سكني مميّز في مكة، في فئة كل مطوّر فيها بيعلن نفس المواصفات. تلال كانت محتاجة تبيع إحساس تربية عيلة في مكان له معنى.',
      strategy:
        'القرب من الحرم مش ميزة، ده أسلوب حياة. بنيت الحملة على «حيث تجد الحياة مكانها»: لحظات عائلية وضوء المغرب والمدينة في الكادر، عشان الموقع نفسه يوصّل الرسالة.',
    },
    'fresh-valley': {
      title: 'فريش فالي، فاخرة بطبيعتها',
      tagline: 'منتجات يومية تبان فاخرة عن قصد.',
      category: 'أغذية وتجزئة · سوشيال',
    },
    gf: {
      title: 'جيلت فري، بلا ندم، طعم بس',
      tagline: 'حلويات تبان دسمة وتفضل خفيفة.',
      category: 'أغذية وتجزئة · سوشيال',
    },
    'the-nine': {
      title: 'ذا ناين، قهوة ومطبخ',
      tagline: 'قهوة مختصة بشكل أبيض وأسود نظيف.',
      category: 'أغذية وتجزئة · سوشيال',
    },
    'hr-link': {
      title: 'إتش آر لينك، برمجيات تُباع ببساطة',
      tagline: 'نظام موارد بشرية بإحساس سهل، مش تقني.',
      category: 'SaaS · سوشيال',
    },
    'next-academy': {
      title: 'نكست أكاديمي، مهارات تجذب',
      tagline: 'بوستات تدريب مبنية لتحويل الاهتمام إلى تسجيل.',
      category: 'تعليم · سوشيال',
    },
    'brand-vitals': {
      title: 'براند فايتلز، تسويق مبني بالمكعبات',
      tagline: 'نصائح تسويق شكلها صندوق ألعاب وتوصل كلكمة.',
      category: 'تسويق · سوشيال',
    },
  },
  ai: {
    label: "سير عمل الذكاء الاصطناعي",
    h2a: "الطريقة",
    h2i: "أولًا",
    h2b: "، وبعدها الشغل.",
    note: "إنتاجان مخطّطان كنظام: اقرأ الفلو الأول، وبعدها شوف نتيجته.",
    pick: "اختر إنتاجًا",
  },
  master: {
    label: "الفيجوالز الرئيسية",
    h2a: "لوحات الحملات، و",
    h2i: "الفكرة",
    h2b: " اللي وراها.",
    note: "صور رئيسية مع المفهوم ودوري والحِرفة اللي بنتها. اضغط أي لوحة لتكبيرها.",
    expand: "عرض أكبر",
    close: "إغلاق",
  },
  socialCards: {
    label: "تصاميم سوشيال ميديا",
    h2a: "علامة واحدة،",
    h2i: "نظام واحد",
    h2b: "، وكل البوستات.",
    note: "كل علامة ليها صورة رئيسية ونظام بوستات قابل للتكرار، فالفيد يفضل متّسق بسرعة النشر.",
    keyVisual: "الصورة الرئيسية",
    posts: "تصميم",
    viewAll: "شوف السِت كامل →",
  },
  story: {
    label: "ستوري بورد",
    h2a: "كل فيلم بيتُرسم",
    h2i: "قبل",
    h2b: " ما يتصوّر.",
    note: "لوحات إطار بإطار تثبّت القصة واللقطات والإيقاع قبل بدء الإنتاج.",
    board: "لوحة",
  },
  clients: {
    label: "العملاء",
    h2a: "علامات",
    h2i: "اشتغلت معاها",
    h2b: ".",
    note: "عبر العقارات والأغذية والتجزئة والتقنية والضيافة والتعليم في مصر والسعودية والكويت.",
  },
  services: {
    label: "الخدمات",
    h2a: "ماذا أستطيع أن",
    h2i: "أفعل",
    h2b: "لعلامتك.",
    note: "متاح لأدوار دوام كامل وعن بُعد وفريلانس وهجين، ",
    noteLink: "ابدأ محادثة ↗",
    items: [
      {
        title: "الهوية البصرية",
        desc: "شعارات وأنظمة بصرية وتغليف وأدلّة استخدام، هويات تتوسّع من كرت العمل حتى أسطول التوزيع.",
        tags: ["الشعار", "النظام البصري", "التغليف"],
      },
      {
        title: "الحملات والصور الرئيسية",
        desc: "حملات إعلانية وصور بطولية للعقارات والسيارات والتقنية والضيافة، من الفكرة إلى الفن النهائي.",
        tags: ["فكرة الحملة", "صور رئيسية", "عربي/إنجليزي"],
      },
      {
        title: "أنظمة السوشيال ميديا",
        desc: "فيدات متّسقة قابلة للتكرار، شبكات وقوالب وأنظمة محتوى تحافظ على الجودة بسرعة النشر.",
        tags: ["قوالب", "تصميم محتوى", "أنظمة فيد"],
      },
      {
        title: "الإخراج الفني والإبداعي",
        desc: "قيادة المصممين وامتلاك اللغة البصرية، بريفات ومراجعات ومعايير ترفع مستوى الإنتاج كله.",
        tags: ["قيادة فريق", "بناء المفاهيم", "ضبط الجودة"],
      },
      {
        title: "إنتاج بالذكاء الاصطناعي",
        desc: "صور بمستوى الحملات وتعليق صوتي بالذكاء الاصطناعي، مُخرجة ومنتقاة ومعالَجة باحترافية.",
        tags: ["تصوير AI", "هندسة البرومبت", "تعليق صوتي AI", "ريتاتش"],
      },
      {
        title: "الموشن والويب",
        desc: "ريلز وبرومو ومونتاج، ومواقع مصمَّمة ومبنية بالكامل بالتطوير المعزّز بالذكاء الاصطناعي، مثل هذا الموقع.",
        tags: ["فيديو وريلز", "موشن جرافيك", "تصميم مواقع"],
      },
    ],
  },
  motion: {
    label: "موشن وفيديو",
    h2a: "حين لا تكفي",
    h2i: "الصورة الثابتة",
    h2b: ".",
    note: "أفلام علامات وريلز وأنيميشن، اضغط السماعة للصوت، أو كبّر أي مقطع.",
    landscape: "أفقي",
    portrait: "رأسي",
  },
  type: {
    label: "تصميم حروف",
    h2a: "حروفٌ تُرسَم",
    h2i: "باليد",
    h2b: ".",
    note: "حروف عربية ولاتينية مخصّصة، لوجوتايبات وعناوين حملات وكلمات مرسومة حرفًا حرفًا.",
  },
  web: {
    label: "فايب كودينج",
    h2a: "أصمّم، ثم",
    h2i: "أشحن الكود",
    h2b: ".",
    note: "مواقع حيّة صمّمتها وبنيتها بالتطوير المعزّز بالذكاء الاصطناعي. حتى هذا البورتفوليو مبني بنفس الطريقة. اختر موقعًا لمعاينته.",
    live: "مباشر ↗",
    visit: "افتح الموقع",
    sites: "موقع منشور",
  },
  social: {
    label: "تصاميم مختارة، جدار متواصل من الأعمال",
    browse: "تصفّح الأعمال ↑",
  },
  hire: {
    avail: "دوام كامل · عن بُعد · فريلانس · هجين",
    h2a: "عندك علامة تحتاج",
    h2i: "اتجاهًا",
    h2b: "؟",
    body: "أنا متاح لأدوار دوام كامل وعن بُعد وفريلانس وهجين عبر مصر · السعودية · الكويت. احكِ لي ما تبنيه، وسأخبرك كيف يوصله التصميم.",
    wa: "راسلني واتساب ↗",
    all: "كل وسائل التواصل",
  },
  footer: {
    blurb:
      "مصمم أول وقائد فريق مقيم في مصر، أعمل عبر مصر · السعودية · الكويت. متاح لأدوار دوام كامل وعن بُعد وفريلانس وهجين.",
    siteCol: "الموقع",
    connectCol: "تواصل",
    rights: "صُمّم وأُخرج فنيًا وبُرمج داخليًا.",
    backTop: "العودة للأعلى ↑",
  },
  about: {
    label: "عنّي",
    heroBio:
      "أكتر من خمس سنين بحوّل فيها مشاكل الشغل لإجابات بصرية: هويات وحملات وأنظمة سوشيال لشركات في مصر والسعودية والكويت. دلوقتي بقود فريق تصميم، وبدوّر على المكان الجاي اللي أبني فيه فريق.",
    intro1: "مصمّم يقود، يتعامل مع كل علامة بوصفها",
    introAccent: "مشكلة عمل",
    intro2: "لها إجابة إبداعية.",
    bio1: "أنا محمد طارق، مصمم أول وقائد فريق، مقيم في مصر وبخبرة مهنية عبر الأسواق المصرية والسعودية والكويتية، أركّز على تصميم نظيف واستراتيجي مدفوع بالأداء يقوّي هوية العلامة ويخدم أهداف التسويق الحقيقية.",
    bio2: "أعمل عبر البراندينج والحملات وأنظمة السوشيال والصور الرئيسية والموشن، متمكّن من فوتوشوب وإليستريتور وتصميم الواجهات وأدوات الذكاء الاصطناعي الإبداعية التي أستخدمها لابتكار وتسليم أعمال حديثة تناسب أسواق الشرق الأوسط. وإلى جانب عمل العملاء، أدرّس الجرافيك ديزاين كمُحاضر وأوجّه الجيل القادم من المصممين.",
    coreFocus: "التركيز الأساسي",
    traitsLabel: "سمات شخصية",
    focus: ["تصميم بصري 2D", "أنظمة العلامات", "هندسة برومبت AI", "تعليق صوتي AI"],
    traits: [
      "مفكّر إبداعي واستراتيجي",
      "مدفوع بالأداء",
      "مهتم بالتفاصيل",
      "سريع التعلّم والتكيّف",
      "اتساق بصري قوي",
      "لاعب فريق تعاوني",
    ],
  },
  exp: {
    label: "الخبرات",
    h2a: "الشركات التي",
    h2i: "صنعتني",
    h2b: ".",
    note: "عبر مصر والسعودية، الأحدث أولًا. من مصمّم جرافيك، إلى التدريس، إلى قيادة فريق فني.",
    now: "الآن",
    promoted: "↑ ترقية",
    returned: "↩ عاد ليقود",
    earlier: "سابقًا في Osolutions · ثلاث سنوات من الترقيات",
    filterHint: "تصفية حسب نوع الالتزام",
    all: "كل الأدوار",
    fullTime: "دوام كامل",
    partTime: "جزئي · عن بُعد",
  },
  teach: {
    label: "التدريس",
    h2a: "لا أقود المصممين فقط، ",
    h2i: "أنا أصنعهم",
    h2b: ".",
    note: "مُحاضر في أربع أكاديميات، ومستشار عند الطلب، أزور الفرق لحل مشكلات التصميم على أرض الواقع.",
    statNote: "قرابة ١٢٠٠ طالب تخرّجوا عبر ٤٩ دفعة، الأرقام تقريبية، وما زالت تنمو.",
    stats: [
      { n: "~١٢٠٠", l: "طالب متخرّج" },
      { n: "٤٩", l: "دفعة تدريبية" },
      { n: "٤", l: "أكاديميات" },
    ],
    current: "حاليًا",
    role: "مُحاضر تصميم",
    academies: [
      {
        name: "SOIC، مدرسة السينما",
        logo: "/orgs/soic.webp",
        now: true,
        desc: "تدريس حِرفة التصميم داخل مدرسة لصناعة الأفلام، السرد البصري والكي-آرت وتفكير الحملات للسينما.",
      },
      {
        name: "EDUX أكاديمي",
        logo: "/orgs/edux.webp",
        now: true,
        desc: "مسارات جرافيك ديزاين تأخذ الطلاب من الأساسيات حتى تنفيذٍ جاهز للبورتفوليو.",
      },
      {
        name: "Easily",
        now: false,
        desc: "رحلة أساسيات كاملة، فوتوشوب وإليستريتور وفيجما؛ حملات إعلانية وUI/UX ومودبورد وستوري بورد وإنسايتس وتطوير مفاهيم وتنفيذ.",
      },
      {
        name: "راية أكاديمي",
        logo: "/orgs/raya.webp",
        now: false,
        desc: "دفعات جرافيك عملية، فوتو مانيبيوليشن وصفحات هبوط وبراندينج، مشروعًا بمشروع.",
      },
    ],
  },
  process: {
    label: "منهجية العمل",
    h2a: "من البريف إلى",
    h2i: "قرار",
    h2b: ".",
    note: "الإخراج هو صناعة القرار، المسار الذي آخذ فيه كل علامة، من الفهم حتى التنفيذ.",
    steps: [
      {
        n: "01",
        title: "البحث",
        body: "أبدأ من العمل والسوق والجمهور، ما الذي تحتاج العلامة تحقيقه، وما الذي يقوله الجميع بالفعل.",
      },
      {
        n: "02",
        title: "الإنسايت",
        body: "أجد الحقيقة الواحدة التي تفتح العمل، التوتّر الذي يجعل الناس تهتم. الإنسايت هو الاستراتيجية في جملة.",
      },
      {
        n: "03",
        title: "الفكرة",
        body: "أترجم الإنسايت إلى فكرة إبداعية كبيرة تكفي لتعيش عبر القنوات، منصة، لا بوستر.",
      },
      {
        n: "04",
        title: "الاتجاه الفني",
        body: "أحدّد اللغة البصرية: الخط واللون والضوء والنبرة. تتحوّل الفكرة إلى عالمٍ بقواعد يبني عليها الجميع.",
      },
      {
        n: "05",
        title: "التنفيذ",
        body: "أحوّلها إلى واقع وأحافظ على المستوى في كل نقطة تماس، من الإطار البطولي حتى أصغر ستوري.",
      },
    ],
  },
  skills: {
    label: "القدرات",
    groups: [
      {
        title: "الإخراج والاستراتيجية",
        items: ["إخراج إبداعي", "استراتيجية علامات", "تصميم حملات", "تفكير إبداعي"],
      },
      {
        title: "الحِرفة والأنظمة",
        items: ["هوية بصرية", "أنظمة سوشيال ميديا", "موشن ديزاين", "اتصال تسويقي"],
      },
      {
        title: "الإنتاج",
        items: ["فوتو مانيبيوليشن", "صور رئيسية", "تصميم واجهات", "هندسة برومبت AI", "تعليق صوتي AI (ElevenLabs)", "فايب كودينج"],
      },
    ],
  },
  tools: {
    label: "الأدوات",
    h2a: "أدوات الحِرفة، مشحوذة بـ",
    h2i: "الذكاء الاصطناعي",
    h2b: ".",
    aiCol: "أدوات AI",
    craftCol: "تصميم وموشن",
  },
  vision: {
    label: "الرؤية",
    h2a: "أريد أن أحوّل مشكلة العمل إلى",
    h2i: "الفكرة",
    h2b: "التي يلتفّ حولها الجميع.",
    pillars: [
      {
        k: "أين أنا",
        v: "قائد فريق فني بحِرفة مصمّم وحدس استراتيجي، أقود الفريق فعلًا وأبني أعمالًا تُحقق نتائج في السوق.",
      },
      {
        k: "إلى أين أتجه",
        v: "الإخراج الإبداعي: امتلاك المفاهيم من البداية للنهاية، وصياغة اللغات البصرية، ورفع حِرفة من حولي.",
      },
      {
        k: "لماذا الإخراج",
        v: "أقوى أعمالي لم تكن يومًا عن الزخرفة، بل عن القرارات. هناك تلتقي الاستراتيجية والحِرفة والقيادة.",
      },
    ],
  },
  contact: {
    label: "تواصل",
    h2a: "لنصنع عملًا",
    h2i: "يُتذكَّر.",
    body: "متاح لأدوار جديدة ومشاريع فريلانس وتعاونات إبداعية عبر مصر · السعودية · الكويت. إن كنت تبني شيئًا طموحًا، يسعدني أن أسمع عنه.",
    labels: {
      Email: "البريد",
      WhatsApp: "واتساب",
      Phone: "الهاتف",
      LinkedIn: "لينكد إن",
    },
    copy: "نسخ",
    copied: "تم النسخ",
    open: "فتح",
  },
  case: {
    allWork: "كل الأعمال",
    letsTalk: "لنتحدث",
    challenge: "التحدّي",
    solution: "الحل",
    ctaA: "عندك علامة تستحق البناء؟",
    ctaI: "لنتحدث.",
    ctaBtn: "ابدأ محادثة ↗",
    cont: "تابع",
    readMore: "شاهد الحالة كاملة",
    showAll: "عرض الكل",
    finalVideos: "الفيديوهات النهائية",
    interactive: "تفاعلي",
    prev: "السابق",
    next: "التالي",
  },
};

export const dict = { en, ar };
